<?xml version="1.0" encoding="utf-8"?><Database Name="dccmoviestorage" Class="MovieClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dccmoviestorage.mssql.somee.com;Initial Catalog=dccmoviestorage;User ID=donaldIMBD_SQLLogin_3" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dccmoviestorageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FavoriteMovies" Member="FavoriteMovies">
    <Type Name="FavoriteMovy">
      <Column Name="P_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rated" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Released" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Runtime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Plot" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Director" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Writer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IMDbRating" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PosterUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewReleaseMovies" Member="NewReleaseMovies">
    <Type Name="NewReleaseMovy">
      <Column Name="P_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rated" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Released" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Runtime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Plot" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Director" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Writer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IMDbRating" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PosterUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WantToSeeMovies" Member="WantToSeeMovies">
    <Type Name="WantToSeeMovy">
      <Column Name="P_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rated" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Released" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Runtime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Plot" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Director" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Writer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IMDbRating" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PosterUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>